apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: blue-grafana
  namespace: monitor
spec:
  client:
    preferService: true
  ingress:
    enabled: True
    pathType: Prefix
    path: "/"
  config:
    log:
      mode: console
      level: info
    security:
      admin_user: "admin"
      admin_password: "admin"
    auth.anonymous:
      enabled: True
    users:
      viewers_can_edit: true    
  service:
    name: "grafana-operator-controller-manager-metrics-service"
    labels:
      app: "grafana"
      type: "grafana-operator-controller-manager-metrics-service"
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  resources:
    # Optionally specify container resources
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi